/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOGICA_H_RPCGEN
#define _LOGICA_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct conta {
	int ID;
	float Saldo;
};
typedef struct conta conta;

struct transacao {
	int ID;
	int codigo;
	double valor;
};
typedef struct transacao transacao;

#define PROG 1048576
#define VERSAO 100

#if defined(__STDC__) || defined(__cplusplus)
#define solicita_codigo 1
extern  int * solicita_codigo_100(void *, CLIENT *);
extern  int * solicita_codigo_100_svc(void *, struct svc_req *);
#define solicita_abertura 2
extern  int * solicita_abertura_100(int *, CLIENT *);
extern  int * solicita_abertura_100_svc(int *, struct svc_req *);
#define solicita_autenticacao 3
extern  int * solicita_autenticacao_100(transacao *, CLIENT *);
extern  int * solicita_autenticacao_100_svc(transacao *, struct svc_req *);
#define solicita_fechamento 4
extern  int * solicita_fechamento_100(transacao *, CLIENT *);
extern  int * solicita_fechamento_100_svc(transacao *, struct svc_req *);
#define solicita_deposito 5
extern  int * solicita_deposito_100(transacao *, CLIENT *);
extern  int * solicita_deposito_100_svc(transacao *, struct svc_req *);
#define solicita_retirada 6
extern  int * solicita_retirada_100(transacao *, CLIENT *);
extern  int * solicita_retirada_100_svc(transacao *, struct svc_req *);
#define solicita_consulta 7
extern  conta * solicita_consulta_100(transacao *, CLIENT *);
extern  conta * solicita_consulta_100_svc(transacao *, struct svc_req *);
extern int prog_100_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define solicita_codigo 1
extern  int * solicita_codigo_100();
extern  int * solicita_codigo_100_svc();
#define solicita_abertura 2
extern  int * solicita_abertura_100();
extern  int * solicita_abertura_100_svc();
#define solicita_autenticacao 3
extern  int * solicita_autenticacao_100();
extern  int * solicita_autenticacao_100_svc();
#define solicita_fechamento 4
extern  int * solicita_fechamento_100();
extern  int * solicita_fechamento_100_svc();
#define solicita_deposito 5
extern  int * solicita_deposito_100();
extern  int * solicita_deposito_100_svc();
#define solicita_retirada 6
extern  int * solicita_retirada_100();
extern  int * solicita_retirada_100_svc();
#define solicita_consulta 7
extern  conta * solicita_consulta_100();
extern  conta * solicita_consulta_100_svc();
extern int prog_100_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_conta (XDR *, conta*);
extern  bool_t xdr_transacao (XDR *, transacao*);

#else /* K&R C */
extern bool_t xdr_conta ();
extern bool_t xdr_transacao ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOGICA_H_RPCGEN */
