/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "logica.h"

int codigo_atual = 0;
conta* CONTAS[50];

int *
solicita_codigo_100_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result = codigo_atual++;

	return &result;
}

int *
solicita_abertura_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;
	int i;

	for(i = 0; i < 50; i++){
		if(CONTAS[i] == NULL){
			CONTAS[i] = &(argp->conta_cliente);
			CONTAS[i]->ID = i;
			CONTAS[i]->Saldo = 0;
			result = 1;
		}
		else result = -1;
	}

	return &result;
}

int *
solicita_autenticacao_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
solicita_fechamento_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
solicita_deposito_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
solicita_retirada_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
solicita_consulta_100_svc(transacao *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
