/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "logica.h"

bool_t
xdr_conta (XDR *xdrs, conta *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->ID))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->Saldo))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_transacao (XDR *xdrs, transacao *objp)
{
	register int32_t *buf;

	 if (!xdr_conta (xdrs, &objp->conta_cliente))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->codigo))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->valor))
		 return FALSE;
	return TRUE;
}
